USE [productsstore]
GO

INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee10' ,'Park Hyatt-spa','spa','https://hyderabad.park.hyatt.com/en/hotel/activities/hotel-activities/spa.html','Road Number 2, Sri Nagar Colony, Kamalapuri Colony, Banjara Hills, Hyderabad, Telangana 500073',4.5)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee11' ,'O2 Spa','spa','https://www.o2spa.org/','3rd Floor, GVK One Mall, Road Number 1, Balapur Basthi, Banjara Hills, Hyderabad, Telangana 500034',3.0)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee12' ,'O2 Spa Boulder Hill','spa','http://www.o2spa.org/locations/india/spa-in-hyderabad/boulder-hills-hyderbad/','Boulder Hills, Madhava Reddy Colony, Gachibowli, Hyderabad, Telangana 500032',3.2)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee13' ,'Meghavi - Spa, Salon & O Cafe','spa','http://www.meghavispa.com/','34A Meghavi, MLA Colony, Road No : 12, Banjara Hills, Hyderabad, Telangana 500034',4.9)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee14' ,'The 5th Element Spa','spa','http://www.thefifthelement.in/','259, Road No. 72, Dargha Road, Near Whisper Valley, Jubilee Hills, Film Nagar, Hyderabad, Telangana 500033',4.5)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee15' ,'Sapphire Spa','spa','http://thesapphirespa.com/','Usha Jubilee Town Apartment, Road Number 36, Jubilee Hills, Opposite, Jubilee Hills Police Station, Hyderabad, Telangana 500033',3.5)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee16' ,'Green Mint Spa','spa','https://greenmintspa.com/','26, Vahini nagar, Karkhana, Hyderabad, Telangana 500009',2.1)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee17' ,'The Spa','spa','https://hyderabad.hyatthotels.hyatt.com/en/hotel/activities/hotel-activities/spa.html','Jayabheri Silicon Towers, Hitech City Rd, Financial District, Gachibowli, Hyderabad, Telangana 500032',4.6)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee18' ,'Soul Spa & Salon','spa','http://www.welcometosoul.com/en/about.html','NBK Building, N.Vasundhara Devi, H.No 31&36 co-op hb Society Jubilee Hills, Jubilee Hills, Hyderabad, Telangana 500033',4.3)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee19' ,'Opium Spa','spa','http://opiumspa.com/','Shop No. 1, Ground Floor, City Center Mall, Road No. 1, Banjarahills, Hyderabad, Telangana 500034',3.9)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee20' ,'Pink Ladies Gym Ameerpet','fitness center','http://pinkfitness.in/ameerpet','7-1-71/H, Divya Shakthi Apartment, Dharam Karam Road, Kalyan Nagar Phase 1, Ameerpet, Hyderabad, Telangana 500016',3.5)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee21' ,'Fitness ONE','firness center','http://fitnessone.in/kondapur/','Plot No. 5, Park View Building, 2nd Floor, Above Heritage Fresh, Opp, Botanical Garden Road, Venkat Enclave, Whitefields, Kondapur, Hyderabad, Telangana 500084',3.1)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee22' ,'Ozone Fitness & Spa','fitness center','http://www.ozoneclubs.com/home.php','No. 6-3-349/20, Banjara Hills, Road No. 1, Hyderabad, Telangana 500034',3.5)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee23' ,'Cloud Fitness | GYMS','fitness center','http://www.thecloudfitness.com/','Opposite Gachhibowli Road, The Platina, Jayabheri Enclave, Gachibowli, Hyderabad, Telangana 500032',4.3)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee24' ,'The Stallions Gym','fitness center','http://www.stallionsgym.com/','No. 1-98/11/12, 2nd Floor, Above Corporaton Bank, Behind Vodafone Showroom, Madhapur, Hyderabad, Telangana 500081',4.5)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee25' ,'Potens Fitness','fitness center','https://potens.in/','Plot No. 2, Adjacent to InOrbit Mall, Durgamma Cheruvu Rd, Vittal Rao Nagar, Hitech City, Madhapur, Hyderabad, Telangana 500081',4.6)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee26' ,'Steel Gym','fitness center','http://www.steelgym.in/','1355, Neharika Jubilee One, Jubilee Hills Road No.1 and Road.45 Junction,, Adjacent to HDFC bank, Hyderabad, Telangana 500033',4.4)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee27' ,'Lions MMA, Mixed Martial Arts & Fitness Center','fitness center','http://tamma.in/','# 8-1-35/A/21 Movie Planet Building,, Near Galaxy Theatre, Above Movie Planet 5th Floor, Hyderabad, Telangana 500008',3.2)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee28' ,'Speed fitness gym','fitness center','https://www.facebook.com/speedfitnesskphb/?ref=aymt_homepage_panel','plot no.3/A, Phase-5, surya enclave, opp Brand Factory Rd, Kukatpally, Hyderabad, Telangana 500072',4.9)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee29' ,'Anytime Fitness','fitness center','http://www.anytimefitness.co.in/gyms/IN-1005/hyderabad-andhra-pradesh-500033','Plot No. 71, Road No. 1 & 9, Besides TV 5 Office, Jubilee Hills, Hyderabad, Telangana 500033',4.4)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee30' ,'Mirrors','salon','http://mirrorsspaandsalon.com/','Plot No.66, Park View Enclave, Road No.1, Jubilee HIlls, Hyderabad, Telangana 500033',4.3)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee31' ,'Bubbles Hair & Beauty - Jubilee Hills','salon','http://bubblesindia.com/','Plot No 21B, Journalist Colony \"B\", Opp.KBR Park, Jubilee Hills, Hyderabad, Telangana 500033',3.6)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee32' ,'Lucas Academy & Salon','salon','http://www.lucassalon.com/','4th Floor, Fortune Atrium, Road No. 36, Jubilee Hills, Opp. Chutneys, Hyderabad, Telangana 500033',4.2)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee33' ,'Envi Salon & Spa','salon','http://www.envisalon.in/','No. 8-2-684/3/162, Road No. 12, Banjara Hills, Hyderabad, Telangana 500034',4.4)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee34' ,'Manea the salon-manea.in','salon','http://www.manea.in/','No. 8-2-120/112, 1st Floor, Park View Estate, Road No. 2, Banjara Hills, Hyderabad, Telangana 500034',3.7)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee35' ,'Manea The Salon','salon','http://www.manea.in/','No. 1-98/7/2/5A, 1st Floor, Above Karachi Bakery, Madhapur, Hyderabad, Telangana 500071',3.9)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee36' ,'Lakme Salon','salon','http://www.lakmeindia.com/','No. 16-11-477/6/1, First Floor, RD Towers, Dilsukhnagar Main Road, Dilsukhnagar, Beside Bajaj Electronics, Hyderabad, Telangana 500060',3.2)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee37' ,'Bubbles Hair & Beauty - Orange County','salon','http://bubblesindia.com/','Financial District, Nanakram Guda, Hyderabad, Telangana 500032',3.2)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee38' ,'Paris De Salon','salon','http://parisdesalon.com/','#286/A Opp. KBR Park, Road # 12. MLA Colony, -500034',4.4)
INSERT INTO [dbo].[Businesses] ([Id] ,[BusinessName] ,[BusinessType] ,[Link] ,[Address] ,[Rating]) VALUES ('1becf483-2ab4-427d-916e-3aaf84a1ee39' ,'Naturals Family Salon & Spa','salon','http://www.naturals.in/','Plot No. 9&10, 1st Floor, Indira SNR Plaza, HUDA Colony, Gangaram, Chandanagar, Church Rd, Hyderabad, 500050',2.0);

GO


